### PR TITLE
fixing errors

### PR DESCRIPTION
**Pull request by giovannism20**
I cloned the project and realized some errors that were causing the app to not work.

### CODE REVIEW

**Comment by hsavit1** [comment]
So pretty much alamofire needed to be upgraded to 4.2? @GiovanniSM20

**Comment by giovannism20** [comment]
"needed" to be updated and also had some syntax errors that were causing the app to not work, i also increased performance @hsavit1

**Comment by giovannism20** [comment]
such that :

`let alert = UIAlertController(title: "Could not get any response from the server", message: "Error: \(response.error)", style = .Alert)`

the new :

`UIAlertController(title: "Check-in realizado com sucesso!", message: nil, preferredStyle: UIAlertControllerStyle.alert)`

**Comment by hsavit1** [comment]
It looks like you changed an error message alert to a success alert? @GiovanniSM20

**Comment by giovannism20** [comment]
i just changed the title, i put more as an example of how it can be implemented @hsavit1

**Pull request closed without merging**
